qt_add_library(sage_ui STATIC
    ui/dialogs/SageFramelessDlg.cpp
    ui/dialogs/SageFramelessDlg.h
    ui/dialogs/SageMessageBoxDlg.cpp
    ui/dialogs/SageMessageBoxDlg.h
    ui/models/SageSidebarModel.cpp
    ui/models/SageSidebarModel.h
    ui/panels/SageSidebarPanel.cpp
    ui/panels/SageSidebarPanel.h
    ui/style/SageDesignDefine.h
    ui/style/SageFontCatalog.cpp
    ui/style/SageFontCatalog.h
    ui/style/SageFontRegistry.cpp
    ui/style/SageFontRegistry.h
    ui/style/SageIconEngine.cpp
    ui/style/SageIconEngine.h
    ui/style/SageStyle.cpp
    ui/style/SageStyle.h
    ui/style/SageStyleDefine.h
    ui/widgets/SageButton.cpp
    ui/widgets/SageButton.h
    ui/widgets/SageDialogCaptionBar.cpp
    ui/widgets/SageDialogCaptionBar.h
    ui/widgets/SageLabel.cpp
    ui/widgets/SageLabel.h
    ui/widgets/SageSidebarDelegate.cpp
    ui/widgets/SageSidebarDelegate.h
    ui/widgets/SageSurface.cpp
    ui/widgets/SageSurface.h
    ui/window/SageMainWindow.cpp
    ui/window/SageMainWindow.h
)

target_include_directories(sage_ui
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}
)

target_link_libraries(sage_ui
    PUBLIC
        Qt::Widgets
        sage_core
        sage_define
)
