cmake_minimum_required(VERSION 3.22)

project(SageQt VERSION 1.0.0 LANGUAGES CXX)

set(SAGE_ORGANIZATION_NAME "Sage")
set(SAGE_APPLICATION_NAME "SageQt")
set(SAGE_COMPANY_NAME "Sage")
set(SAGE_PRODUCT_NAME "SageQt")
set(SAGE_COPYRIGHT "Copyright © 2026 Sage")
set(SAGE_BUNDLE_IDENTIFIER "com.sage.sageqt")

enable_testing()

add_subdirectory(SageQt)
