include(GNUInstallDirs)

install(TARGETS SageQt
    BUNDLE DESTINATION .
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

qt_generate_deploy_app_script(
    TARGET SageQt
    OUTPUT_SCRIPT SAGE_DEPLOY_SCRIPT
    NO_TRANSLATIONS
    NO_UNSUPPORTED_PLATFORM_ERROR
)
install(SCRIPT ${SAGE_DEPLOY_SCRIPT})

if(NOT APPLE)
    install(FILES ${SAGE_LICENSE_FILES} DESTINATION ${CMAKE_INSTALL_BINDIR}/licenses)
endif()

if(UNIX AND NOT APPLE)
    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/../SageQt.desktop DESTINATION ${CMAKE_INSTALL_DATADIR}/applications)
    install(FILES ${SAGE_APP_ICON_PNG}
        DESTINATION ${CMAKE_INSTALL_DATADIR}/icons/hicolor/256x256/apps
        RENAME ${SAGE_APP_ICON_NAME}.png
    )
endif()

set(CPACK_PACKAGE_NAME ${SAGE_PRODUCT_NAME})
set(CPACK_PACKAGE_VENDOR ${SAGE_COMPANY_NAME})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${SAGE_PRODUCT_NAME})
set(CPACK_PACKAGE_INSTALL_DIRECTORY ${SAGE_PRODUCT_NAME})
set(CPACK_PACKAGE_CHECKSUM SHA256)

if(SAGE_PACKAGE_PLATFORM)
    set(CPACK_SYSTEM_NAME ${SAGE_PACKAGE_PLATFORM})
endif()

if(WIN32)
    set(CPACK_GENERATOR ZIP)
elseif(APPLE)
    set(CPACK_GENERATOR DragNDrop)
else()
    set(CPACK_GENERATOR TGZ)
endif()

include(CPack)
